version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    networks:
      - mern-network
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - GENERATE_SOURCEMAP=false
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - mern-network
    volumes:
      - ./client:/app
      - /app/node_modules

networks:
  mern-network:
    driver: bridge